### ISSUE TITLE
Integrate SKU lookup

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/PantryNode#25]

**Comment by kbuffardi** [comment]
This is being discussed in [this thread](https://github.com/ChicoState/PantryNode/discussions/37#discussion-4919441)

**Comment by jayrevolinskyjr** [comment]
I suggest this should stay on the backlog until all dependency issues are resolved

**Comment by jayrevolinskyjr** [comment]
### These subtasks _must_ be completed first:

- [ ] Confirm that dependencies are ready for SKU lookup feature implementation. Requires confirmation from someone in frontend and database teams.
- [ ] Determine the database design for tracking inventory and their relevant components (value, ID, name, quantity, etc.) Might need a discussion about this.

### These subtasks _must_ be completed after the first two subtasks but can be developed synchronously:

#### Backend
- [ ] Implement the database as we determined in the previous task.
- [ ] Build function calls for the frontend.

#### Frontend
- [ ] Build a basic SKU lookup page. Depending on our API or dependency, could involve a camera and/or an input form.

Communication between frontend and backend teams for this feature will be key.

**Comment by jayrevolinskyjr** [comment]
Considering the subtasks I mentioned above, it is very likely that they will be separate issues entirely and will need to be discussed further [here](https://github.com/ChicoState/PantryNode/discussions/71) before we can even consider taking this issue out of the backlog.

**Comment by jayrevolinskyjr** [comment]
As per my Discussion with @ysiddhapura in-class today, there is an issue where Quagga returns 404 in the PantryNode app. This is likely due to a routing or views issue. We decided to have Yashvi implement the scan function to complete her subtask. We determined that the error is related to the button subtask. The error message prints as follows:

> Attaching to node, pantrynode-database-1, pantrynode-db_admin-1
> node                   | 
> node                   | > project@0.0.0 start
> node                   | > ts-node bin/www
> node                   | 
> node                   | Executing (default): SELECT 1+1 AS result
> node                   | Connection has been established successfully.
> node                   | GET / 200 50.017 ms - 5227
> node                   | GET /stylesheets/style.css 200 32.886 ms - 5635
> node                   | GET /images/logo.png 304 15.277 ms - -
> node                   | GET /images/logo_w2.png 304 16.617 ms - -
> node                   | GET /images/magenta.jpg 200 3.917 ms - 168165
> node                   | ClientError [NotFoundError]: Not Found
> node                   |     at /app/app.js:86:10
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> node                   |     at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
> node                   |     at router (/app/node_modules/express/lib/router/index.js:47:12)
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:346:9)
> node                   | Error: Failed to lookup view "error" in views directory "/app/views"
> node                   |     at Function.render (/app/node_modules/express/lib/application.js:597:17)
> node                   |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
> node                   |     at /app/app.js:97:9
> node                   |     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/app.js:86:5
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> node                   | GET /apple-touch-icon-precomposed.png 404 120.429 ms - 1499
> node                   | ClientError [NotFoundError]: Not Found
> node                   |     at /app/app.js:86:10
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> node                   |     at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
> node                   |     at router (/app/node_modules/express/lib/router/index.js:47:12)
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:346:9)
> node                   | GET /apple-touch-icon.png 404 41.669 ms - 1499
> node                   | Error: Failed to lookup view "error" in views directory "/app/views"
> node                   |     at Function.render (/app/node_modules/express/lib/application.js:597:17)
> node                   |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
> node                   |     at /app/app.js:97:9
> node                   |     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/app.js:86:5
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> node                   | GET / 304 7.575 ms - -
> node                   | GET /stylesheets/style.css 304 7.201 ms - -
> node                   | GET /images/logo_w2.png 304 2.544 ms - -
> node                   | GET /images/logo.png 304 2.170 ms - -
> node                   | GET /images/magenta.jpg 304 9.865 ms - -
> node                   | GET /scanner 200 3.158 ms - 725
> node                   | ClientError [NotFoundError]: Not Found
> node                   |     at /app/app.js:86:10
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> node                   |     at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
> node                   |     at router (/app/node_modules/express/lib/router/index.js:47:12)
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:346:9)
> node                   | Error: Failed to lookup view "error" in views directory "/app/views"
> node                   |     at Function.render (/app/node_modules/express/lib/application.js:597:17)
> node                   |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
> node                   |     at /app/app.js:97:9
> node                   |     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/app.js:86:5
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> node                   | GET /public/quagga/quagga.js 404 8.695 ms - 1499
> node                   | GET /scanner 304 4.651 ms - -
> node                   | ClientError [NotFoundError]: Not Found
> node                   |     at /app/app.js:86:10
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> node                   |     at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
> node                   |     at router (/app/node_modules/express/lib/router/index.js:47:12)
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:346:9)
> node                   | Error: Failed to lookup view "error" in views directory "/app/views"
> node                   |     at Function.render (/app/node_modules/express/lib/application.js:597:17)
> node                   |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
> node                   |     at /app/app.js:97:9
> node                   |     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/app.js:86:5
> node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> node                   | GET /public/quagga/quagga.js 404 4.797 ms - 1499
> pantrynode-database-1  | 2023-04-06 17:29:48.402 UTC [26] LOG:  checkpoint starting: time
> pantrynode-database-1  | 2023-04-06 17:29:48.435 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.004 s, total=0.034 s; sync files=2, longest=0.003 s, average=0.002 s; distance=0 kB, estimate=0 kB

It is likely this could be another subtask entirely but the main focus now is to finish subtask 2 and 3.

**Comment by ysiddhapura** [comment]
As per my task, "Write a library for scanning with Quagga", I have imported a quagga.js file from the repo: https://github.com/ericblade/quagga2. I have also created a scanner.js file which implements a function to use the quagga library. I have also created a route in the index.js that links to a scanner.ejs page. Right now I'm getting an error relating to scanner.ejs page, GET /public/quagga/scanner.js 404 39.052 ms - 1500, which I'm not sure how to resolve. 

I'll be submitting a pull request with what I have so far.

**Comment by ysiddhapura** [comment]
> As per my Discussion with @ysiddhapura in-class today, there is an issue where Quagga returns 404 in the PantryNode app. This is likely due to a routing or views issue. We decided to have Yashvi implement the scan function to complete her subtask. We determined that the error is related to the button subtask. The error message prints as follows:
> 
> > Attaching to node, pantrynode-database-1, pantrynode-db_admin-1
> > node                   |
> > node                   | > project@0.0.0 start
> > node                   | > ts-node bin/www
> > node                   |
> > node                   | Executing (default): SELECT 1+1 AS result
> > node                   | Connection has been established successfully.
> > node                   | GET / 200 50.017 ms - 5227
> > node                   | GET /stylesheets/style.css 200 32.886 ms - 5635
> > node                   | GET /images/logo.png 304 15.277 ms - -
> > node                   | GET /images/logo_w2.png 304 16.617 ms - -
> > node                   | GET /images/magenta.jpg 200 3.917 ms - 168165
> > node                   | ClientError [NotFoundError]: Not Found
> > node                   |     at /app/app.js:86:10
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> > node                   |     at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
> > node                   |     at router (/app/node_modules/express/lib/router/index.js:47:12)
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:346:9)
> > node                   | Error: Failed to lookup view "error" in views directory "/app/views"
> > node                   |     at Function.render (/app/node_modules/express/lib/application.js:597:17)
> > node                   |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
> > node                   |     at /app/app.js:97:9
> > node                   |     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/app.js:86:5
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> > node                   | GET /apple-touch-icon-precomposed.png 404 120.429 ms - 1499
> > node                   | ClientError [NotFoundError]: Not Found
> > node                   |     at /app/app.js:86:10
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> > node                   |     at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
> > node                   |     at router (/app/node_modules/express/lib/router/index.js:47:12)
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:346:9)
> > node                   | GET /apple-touch-icon.png 404 41.669 ms - 1499
> > node                   | Error: Failed to lookup view "error" in views directory "/app/views"
> > node                   |     at Function.render (/app/node_modules/express/lib/application.js:597:17)
> > node                   |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
> > node                   |     at /app/app.js:97:9
> > node                   |     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/app.js:86:5
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> > node                   | GET / 304 7.575 ms - -
> > node                   | GET /stylesheets/style.css 304 7.201 ms - -
> > node                   | GET /images/logo_w2.png 304 2.544 ms - -
> > node                   | GET /images/logo.png 304 2.170 ms - -
> > node                   | GET /images/magenta.jpg 304 9.865 ms - -
> > node                   | GET /scanner 200 3.158 ms - 725
> > node                   | ClientError [NotFoundError]: Not Found
> > node                   |     at /app/app.js:86:10
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> > node                   |     at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
> > node                   |     at router (/app/node_modules/express/lib/router/index.js:47:12)
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:346:9)
> > node                   | Error: Failed to lookup view "error" in views directory "/app/views"
> > node                   |     at Function.render (/app/node_modules/express/lib/application.js:597:17)
> > node                   |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
> > node                   |     at /app/app.js:97:9
> > node                   |     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/app.js:86:5
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> > node                   | GET /public/quagga/quagga.js 404 8.695 ms - 1499
> > node                   | GET /scanner 304 4.651 ms - -
> > node                   | ClientError [NotFoundError]: Not Found
> > node                   |     at /app/app.js:86:10
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> > node                   |     at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
> > node                   |     at router (/app/node_modules/express/lib/router/index.js:47:12)
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:346:9)
> > node                   | Error: Failed to lookup view "error" in views directory "/app/views"
> > node                   |     at Function.render (/app/node_modules/express/lib/application.js:597:17)
> > node                   |     at ServerResponse.render (/app/node_modules/express/lib/response.js:1039:7)
> > node                   |     at /app/app.js:97:9
> > node                   |     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/app.js:86:5
> > node                   |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > node                   |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
> > node                   |     at /app/node_modules/express/lib/router/index.js:286:9
> > node                   |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:280:10)
> > node                   |     at /app/node_modules/express/lib/router/index.js:646:15
> > node                   |     at next (/app/node_modules/express/lib/router/index.js:265:14)
> > node                   | GET /public/quagga/quagga.js 404 4.797 ms - 1499
> > pantrynode-database-1  | 2023-04-06 17:29:48.402 UTC [26] LOG:  checkpoint starting: time
> > pantrynode-database-1  | 2023-04-06 17:29:48.435 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.004 s, total=0.034 s; sync files=2, longest=0.003 s, average=0.002 s; distance=0 kB, estimate=0 kB
> 
> It is likely this could be another subtask entirely but the main focus now is to finish subtask 2 and 3.

Yes, not entirely sure what's going on here.

**Comment by ysiddhapura** [comment]
With the updated merges, I tested my additions, and not getting the middleware errors anymore. Just working on figuring out the issue with the scanner.ejs file as nothing is showing up on the page currently.

**Comment by ysiddhapura** [comment]
Rebased the quaggaSKU branch with the current main branch, added the quagga library to the frontend, added scan.tsx file which calls the quagga library, also added a scanner.tsx route and page to test if the quagga is working. Currently, it is able to detect barcodes, now we need to work on connecting it with the backend.

**Comment by briswells** [comment]
@ysiddhapura I was just looking over the sample PR and just a heads up adding a field to the model does not alter the database table. Create_table.sql and dummy_data.sql will need to be updated and the database will need to be re-initialized for the changes in the item model to reflect in the DB.

**Comment by ysiddhapura** [comment]
> @ysiddhapura I was just looking over the sample PR and just a heads up adding a field to the model does not alter the database table. Create_table.sql and dummy_data.sql will need to be updated and the database will need to be re-initialized for the changes in the item model to reflect in the DB.

Thanks for the heads up, we're working on adding to the database currently, so we will add our changes accordingly. 
@Anoushka444 @jayrevolinskyjr

**Comment by briswells** [comment]
Just let me know if you have any questions. I'd be more than happy to help get a API route created.
